services:
  postgres:
    image: postgres:14.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'