CREATE TABLE outbox
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payload        VARCHAR(255),
    type           VARCHAR(255),
    status         VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    delete_after   TIMESTAMP WITHOUT TIME ZONE,
    custom_version BIGINT,
    CONSTRAINT pk_outbox PRIMARY KEY (id)
);